Repository MuhametSmaili/chrome-note-app, pull requests merged in 2022-04, with the labels that each got.

#4 feat: automatic linting and formatting
  .eslintrc.json
  .husky/pre-commit
  .vscode/settings.json
  README.md
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/hello.ts
  styles/Home.module.css
  styles/globals.css
  yarn.lock
Labels: enhancement, feat

#7 refactor: path alias setup
  .eslintrc.json
  components/Hello.tsx
  package-lock.json
  package.json
  pages/index.tsx
  tsconfig.json
  tsconfig.paths.json
Labels: enhancement

#8 feat: draft js
  .eslintrc.json
  .prettierrc
  components/Hello.tsx
  components/NoteEditor.tsx
  components/ToolBar.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  styles/globals.css
  tsconfig.json
Labels: feat

#9 Feat screenshot
  .eslintrc.json
  components/ToolBar.tsx
  extension/background.js
  extension/captureScreen.js
  extension/manifest.json
  package-lock.json
  package.json
  src/utils/getCurrentTab.ts
Labels: feat
